version: '3.8'
services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#        - "8080:8080"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: osiris
    ports:
      - "5432:5432"

  rabbitmq:
      restart: always
      image: rabbitmq:3-management
      ports:
        - "5672:5672"
        - "15672:15672"
      environment:
        RABBITMQ_NODENAME: humc-parent
