version: '3.8'
services:

  rabbitmq:
    restart: always
    image: rabbitmq:3-management
    ports:
      - "5673:5673"
      - "15673:15673"
    environment:
      RABBITMQ_NODENAME: bep3-rabbitmq-node

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: