version: '3.8'
services:

  rabbitmq:
    restart: always
    image: rabbitmq:3-management
    ports:
     - "5672:5672"
     - "15672:15672"
    environment:
      RABBITMQ_NODENAME: bep3-rabbitmq-node

  mongodb:
      image: mongo
      restart: always
      ports:
       -  "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
       - 9092:8081
    environment:
     ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/